In [3]:
import numpy as np
import pandas as pd

In [4]:
a1 = np.array([1,2,3])

In [5]:
a1

array([1, 2, 3])

In [6]:
a2 = np.array([
    [1,2,3],
    [4,5,6]
])

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a3 = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [9,10,11,12],
        [13,14,15,16]
    ]
])

In [9]:
a3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [10]:
type(a3), a3.size, a3.ndim, a3.shape, a3.dtype

(numpy.ndarray, 16, 3, (2, 2, 4), dtype('int64'))

In [14]:
df = pd.DataFrame(a2)

In [15]:
df

,0,1,2
0,1,2,3
1,4,5,6


In [16]:
zeros = np.zeros((4,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
ones = np.ones((4,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
rand1 = np.random.random((4,5))
rand1

array([[0.95643286, 0.49706928, 0.44949629, 0.17567113, 0.68105915],
       [0.4090943 , 0.71293501, 0.1529649 , 0.98505789, 0.46954142],
       [0.24849302, 0.8442542 , 0.3856562 , 0.38704064, 0.35509001],
       [0.67748615, 0.64281536, 0.96930116, 0.70673446, 0.57689268]])

In [26]:
rand2 = np.random.rand(4,5)
rand2

array([[0.1828853 , 0.42212698, 0.83619068, 0.11993991, 0.77835305],
       [0.15019671, 0.15857685, 0.45344243, 0.3150343 , 0.88466936],
       [0.31748323, 0.65479972, 0.45368587, 0.62616937, 0.7591847 ],
       [0.13863589, 0.65609158, 0.32425454, 0.91581906, 0.38466869]])

In [28]:
range1 = np.arange(100, 201, 10)
range1

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200])

In [24]:
shape = (1000, 3, 32, 32)
x = np.ones(shape, dtype=np.uint8) # for example
x

array([[[[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]],

        [[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]],

        [[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]]],


       [[[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]],

        [[1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
  

In [25]:
y = np.array([2, 3, 4])

In [26]:
y

array([2, 3, 4])

In [27]:
y_reshaped = y.reshape(1, 3,1,1)

In [28]:
x + y_reshaped

array([[[[3, 3, 3, ..., 3, 3, 3],
         [3, 3, 3, ..., 3, 3, 3],
         [3, 3, 3, ..., 3, 3, 3],
         ...,
         [3, 3, 3, ..., 3, 3, 3],
         [3, 3, 3, ..., 3, 3, 3],
         [3, 3, 3, ..., 3, 3, 3]],

        [[4, 4, 4, ..., 4, 4, 4],
         [4, 4, 4, ..., 4, 4, 4],
         [4, 4, 4, ..., 4, 4, 4],
         ...,
         [4, 4, 4, ..., 4, 4, 4],
         [4, 4, 4, ..., 4, 4, 4],
         [4, 4, 4, ..., 4, 4, 4]],

        [[5, 5, 5, ..., 5, 5, 5],
         [5, 5, 5, ..., 5, 5, 5],
         [5, 5, 5, ..., 5, 5, 5],
         ...,
         [5, 5, 5, ..., 5, 5, 5],
         [5, 5, 5, ..., 5, 5, 5],
         [5, 5, 5, ..., 5, 5, 5]]],


       [[[3, 3, 3, ..., 3, 3, 3],
         [3, 3, 3, ..., 3, 3, 3],
         [3, 3, 3, ..., 3, 3, 3],
         ...,
         [3, 3, 3, ..., 3, 3, 3],
         [3, 3, 3, ..., 3, 3, 3],
         [3, 3, 3, ..., 3, 3, 3]],

        [[4, 4, 4, ..., 4, 4, 4],
         [4, 4, 4, ..., 4, 4, 4],
         [4, 4, 4, ..., 4, 4, 4],
         ...,
  